apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - _pvc
- ingress-nginx-external
- ingress-nginx-internal
- wildcard-certificate
# - adguard-home
- oxidized
- blocky
- cloudflare-ddns
- etcd
- coredns
- external-dns
- internal-dns
- secret-reflector
- traefik
- oauth2-proxy