---
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64512
  nodeToNodeMeshEnabled: true
  serviceClusterIPs:
    - cidr: 10.43.0.0/16
  serviceExternalIPs:
    - cidr: 10.201.0.0/16