---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-zigbee2mqtt
  namespace: home
  labels:
    service: zigbee2mqtt
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
