---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 6m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.21.0
    env:
      TZ: America/Los_Angeles
      ZIGBEE2MQTT_DATA: /data
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: true
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://mqtt.home.${SECRET_DOMAIN}"
        user: ${ZIGBEE2MQTT_USERNAME}
        password: ${ZIGBEE2MQTT_PASSWORD}
        client-id: zigbee2mqtt
      serial:
        port: /dev/conbee
        adapter: deconz
      advanced:
        log_output:
        - console
        network_key:
        - 204
        - 61
        - 75
        - 23
        - 44
        - 230
        - 24
        - 203
        - 53
        - 5
        - 248
        - 32
        - 50
        - 84
        - 44
        - 159
      frontend:
        port: 8080
      experimental:
        new_api: true
    securityContext:
      privileged: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: true
          # hajimari.io/icon: "mdiTelevisionClassic"
          # hajimari.io/url: 
          # hajimari.io/appName: 
        hosts:
        - host: "zigbee2mqtt.home.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "zigbee2mqtt.home.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: config-zigbee2mqtt
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/conbee
    podAnnotations:
      backup.velero.io/backup-volumes: data
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/custom-conbee", operator: In, values: ["true"]}
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.11.1
        workingDir: "/data"
        args:
        - --user-data-dir
        - "/data/.vscode"
        - --auth
        - "none"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            # ubernetes.io/ingress.class: "internal"
          hosts:
          - host: zigbee2mqtt-config.home.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - zigbee2mqtt-config.home.${SECRET_DOMAIN}
        volumeMounts:
        - name: data
          mountPath: /data
