---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-radarr-4k
  namespace: media
  labels:
    service: radarr-4k
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
