---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-autoscan
  namespace: media
  labels:
    service: autoscan
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
