---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-dizquetv
  namespace: media
  labels:
    service: dizquetv
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
