---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nas-media-pv
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.200.210
    path: /volume1/Media
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-media-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 2Mi
