---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-lidarr
  namespace: media
  labels:
    service: lidarr
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
