---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
  labels:
    service: lidarr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 13.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/lidarr-develop
      tag: v0.8.1.2135
    env:
      TZ: "America/Los_Angeles"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 100
      fsGroup: 568
      supplementalGroups:
        - 100
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "music-box"
          # hajimari.io/url:
          # hajimari.io/appName: 
        hosts:
        - host: "music.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "music.media.${SECRET_DOMAIN}"
      api:
        enabled: true
        primary: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "music.media.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "music.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: config-lidarr
      # nas-merged-media:
      #   enabled: true
      #   existingClaim: nfs-nas-merged-media-pvc
      #   mountPath: "/mnt/unionfs"
      #   # readOnly: true  
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.10.200.240
            path: /mnt/Media/Plex/Merged-Media
        mountPath: /mnt/unionfs
        readOnly: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
