---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudplow
  namespace: media
  labels:
    service: cloudplow
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 15.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: cloudplow
    controllerType: deployment
    image:
      repository: sabrsorensen/alpine-cloudplow
      tag: latest
      pullPolicy: Always
    dnsPolicy: None
    dnsConfig:
      nameservers:
      - "${ROUTER_IP}"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
      CLOUDPLOW_CONFIG: "/shared/Configs/Cloudplow/config.json"
      CLOUDPLOW_LOGFILE: "/dev/null"
      CLOUDPLOW_LOGLEVEL: "INFO"
      CLOUDPLOW_CACHEFILE: "/config/cache.db"
    service:
      main:
        ports:
          http:
           port: 3030
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: config-cloudplow-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /mnt/NFS/Merged-Media
        mountPath: /mnt/unionfs
        readOnly: false
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
        medium: Memory
        sizeLimit: 1Gi
    podAnnotations:
      backup.velero.io/backup-volumes: config
    initContainers:
      git-config:
        image: alpine/git:v2.32.0
        env:
        - name: GITEA_TOKEN
          value: "${SECRET_GITEA_ACCESS_TOKEN}"
        - name: URL
          value: "git.dev.${SECRET_DOMAIN}"
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -o nounset
          set -o errexit
          # sleep 600000000m
          if [ -z "${SECRET_GITEA_ACCESS_TOKEN}" ]; then
            printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
            exit 1
          fi
          git clone --depth 1 "https://${SECRET_GITEA_ACCESS_TOKEN}@git.dev.${SECRET_DOMAIN}/dcplaya/Configs.git" /shared/Configs
          chown -R 1000:1000 /shared/Configs
          exit 0
        volumeMounts:
        - name: shared
          # Path will be /shared/Configs/RClone/default.conf
          mountPath: /shared
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.12.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hosts:
          - host: "vscode-cloudplow.media.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "vscode-cloudplow.media.${SECRET_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: shared
          mountPath: /shared
    probes:
      liveness:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        # cpu: 500m
      limits:
        memory: 1500Mi
