---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-survival-config-v1
  namespace: gaming
  labels:
    service: minecraft-survival
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
