---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.21.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    ## EnableCSI uses the new kubernetes CSI snapshot beta feature
    # features: "EnableCSI"
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://10.10.200.210:9000
          publicUrl: http://10.10.200.210:9000
          #publicUrl: "${SECRET_MINIO_ENDPOINTS}"
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 7h
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = "${SECRET_MINIO_ACCESS_KEY}"
          aws_secret_access_key = "${SECRET_MINIO_SECRET_KEY}"
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    installCRDs: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
        limits:
          cpu: 3000m
          memory: 15360Mi
    # schedules:
    #   daily-backup:
    #     schedule: "0 2 * * *"
    #     template:
    #       ttl: "120h"
    #   weekly-backup:
    #     schedule: "0 3 * * 2"
    #     template:
    #       ttl: "720h"
