---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-gitea
  namespace: dev
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
