---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      existingClaim: config-gitea
    ingress:
      enabled: true
      # ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        # nginx.ingress.kubernetes.io/proxy-body-size: 128m
        # nginx.ingress.kubernetes.io/configuration-snippet: |
        #   proxy_set_header Accept-Encoding "";
        #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/gitea/organizr-dark.css"></head>';
        #   sub_filter_once on;
      hosts:
        - host: "git.dev.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix 
      tls:
      - hosts:
        - "git.dev.${SECRET_DOMAIN}"
    service:
      http:
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
        externalTrafficPolicy: Local
        loadBalancerIP: "${LB_GITEA_IP}"
    gitea:
      admin:
        username: "${SECRET_GITEA_ADMIN_USERNAME}"
        password: "${SECRET_GITEA_ADMIN_PASSWORD}"
        email: "${SECRET_GITEA_ADMIN_EMAIL}"
      config:
        APP_NAME: "Home Gitea"
        server:
          ROOT_URL: "https://git.dev.${SECRET_DOMAIN}"
          MIN_PASSWORD_LENGTH: 8
          DISABLE_SSH: false
          START_SSH_SERVER: false
          SSH_PORT: 22
          SSH_LISTEN_PORT: 22
          SSH_DOMAIN: "ssh.git.dev.${SECRET_DOMAIN}"
          LFS_START_SERVER: true
          # LFS_CONTENT_PATH:
          LFS_JWT_SECRET: "${SECRET_GITEA_ADMIN_PASSWORD}"
          LFS_HTTP_AUTH_EXPIRY: 120m
          LFS_MAX_FILE_SIZE: 0
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        database:
          DB_TYPE: postgres
          HOST: "${EXTERNAL_IP_POSTGRES}:5432"
          NAME: gitea
          USER: "${SECRET_GITEA_POSTGRES_USERNAME}"
          PASSWD: "${SECRET_GITEA_POSTGRES_PASSWORD}"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      database:
        builtIn:
          postgresql:
            enabled: false
      cache:
        builtIn:
          enabled: true
      podAnnotations:
        backup.velero.io/backup-volumes: data
    memcached:
      image:
        repository: bitnami/memcached
        tag: 1.6.10
      service:
        port: 11211
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 13.3.0
      persistence:
        storageClass: "rook-ceph-block"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node00
              - node04
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          kind: Ingress
          name: gitea
        patch:
        - op: add
          path: /spec/ingressClassName
          value: traefik
