# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:2+5FKjb2ToNEp1EiTRkqDEsk1CrfFxJfhH57XMemUQw6a9oCO7SYJFDvUv+6ZbU6rVE8Wc76expHh7OlSFTOqC33COr05SnUj44FS/f5iqYysIqvV32SBbEMZRo0ObQSce1uSDkuqfBfEp+PVExiD7jbj4YwGy/8Q6UY92vKxRsqDluxGoX9x0c=,iv:o5JcTj/wepfjyd8yZeH8Vy6yjwH362ADGbXzgYJ8Z3k=,tag:3oITKmfZBBdRCVdw9s8EoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-17T03:08:57Z"
    mac: ENC[AES256_GCM,data:4Fc4DV0XP7HEWOd8G7fDsEqhon0zhzYDm25BCJEendmVpYzsy3IXKFzppLx9Z/tc4rUm7Z2Zb3lIX80So2FSGA4UVjCAYPVukgRODfL/OjdwPbbl91AiYJzbDjvJuwaVwNvK+VW95Y4kSq5Oqcy4CQ42a6IV11MMjGPslwXroMw=,iv:40PuJJhGAg4rxkf+ed5zsY08KFaDMqT7YRgdFJ4c8Uo=,tag:72331w1Hm3rphIfUnamPnw==,type:str]
    pgp:
        - created_at: "2021-10-17T03:08:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0DF7VD77L2HARAArzKO5XFsOGbet2juj4wsMxbyY71dULpBysXhqdPkXmK4
            +lTl32pK4yz9MOk17DEtJqXudVFN8B2qMDTEq8Bu1+RUlQ4fqU8PN06O20W8MgpR
            f1mkLdfJ7ANkHfwCA/Wuok5KQHtOEh29aB4FTB0uxPolESZC/a1/9vf8T4EHfR8t
            BJEzdIhEYXE/Coyzskpx2nvAdJzLmij7sCjNPP5I1HckRhEv+M6zIHwIImdDqYk3
            BZ3n56b4rzyRjdjcbjfzF/5amlMEIhaPqUP8pQDtX7PY020l0uLBMwODIoRiMJFV
            u1RWTSyGGfXZsNs/HfFmX+IJvXLQed/U/JoEdxO5OWSSknwU0dv//JUT5yg9L7+Y
            YnFeHcVYLIAAUCSw1jmK0FMKkTsCoeI9NC9Vd/BlsXQgbq3q0gsP2dA1LijNq3mz
            72R6KyO5VTGxH0kgQ5KAaqU/4OyBzXExqNNev82nqZTW8jTnqr16Il6mT/1mh4jo
            UjUGdCLcallQlP82RCP3Zu2WZg8g4UcMVvshGMSTKIYsad9gH7sKJ4+ffTSQ2URu
            kUp+G1EWOcp+IcAHcCKsHh0rx3PG7+suXzZwHr63Xk1huLEXt6zpRJ+kdLCp3LtP
            an9X69p4esuVbHZ4JyHVXzc2e1ANo6DcPL4tPfOmvyhBBtjV9lSDQPpuIXcIxXrS
            XgEC7Kip+3wWx4TT7H/BHgh3m3X8251LpKNetrDuwZClHW04X8XWhghvwAEyqoNX
            RMSFC565I6ezR3wbTShYzUVfIHNg8ZbVpQyGh+WO1RmFWTcLQUZWS/fuNg5gkso=
            =nFPe
            -----END PGP MESSAGE-----
          fp: D96D04EF03182786C66C1BBC2B6B833C036DBA10
        - created_at: "2021-10-17T03:08:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6xGzIm50xo4ARAAZoi7ThusKTfhsmEfY7O25g3fQy/dCfomJxxsmCLHo7u2
            JolsxwghxsDUKaQ33a4tzr+px9z3I7ldkgGfvwy0V4mlGBS0usmRuIj2cn8H5jip
            QCDPVBjbxZxmjW+oAc7y9zvAW4CgroYtjgOVrQD8fnnhv7JYHs+P6tM/D3GU7Rp+
            OPZvY929kSeP2DvFtzvUgYy5wVzPWxM3B0F9N7ihKEMeQ9Kdu4gTywZVBDHUKam6
            fOVwaV/x8Tkc7LWshEn7UjUrJspDKkzNg44LE8WxmLYBxFF0SUlIgjWwmy318j+j
            XSZoJWvIEQRT+oNNMWrbzI5eLyNi+p6YRszERID5r/ur/8TTfFnbDCym4hGWaYcg
            OoD6IdVAnwcsRRRkx4xoF4yydYJsl0jhYh/RdDpOfqiQYb4hnsd5Q7Lu7WR9zW5r
            a0hgPux7Af9s+mBlUK+aB/68pkfZagdexKzhVgVWFFck6eA+K5r8RWsa0XV5L/wU
            0aggts/TjBBo58LCyFt+wMnGQAWa9o3kiqURU87ZukloPpxJnjMwgXIFFaEcD0hV
            8X9UrgNE8IWis9xRnwb45fO/cVnHVD02w5+wEnkMv5CPnZcSiJ5g6vJTEx+w7iKU
            tp48glDF/ZQhf+lJ9KXA0086FWR4gbtE7FsDMqdfejKVN/7+DsaNzv+FrqYFPTzS
            5gHnsN4A/sP4VOJfq+ZvU6GKnzcDFDpVmppxB6525zqmcasL1vbdRdannPQbBnku
            z82i+4ytTfSCscihBeWf2fvkJO3k8ji7eFMEG4CQ4U79CeKx1dvXAA==
            =Ccq0
            -----END PGP MESSAGE-----
          fp: 1AA0AC84A4E1A268F9219DEC3D6F4F5FD1A6E398
        - created_at: "2021-10-17T03:08:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9a6pQFKO0vGAQ/7Bgay/XwD9VlOFlkwH/RM4FEtIDzhFKr+LE1GkxGEOdSe
            Mqj1blE9X6Zb2AOZA3J9JSr5+OCfzDRJI7Q92zKDyYqMDBzTMppe022dLxWvk4n4
            qJvejs+Vo3AnJEd4b5I5llxL9DjvSLIGP5iawWtjA3b3vWFZIN2uh4J/tUIq41ON
            g9GZ3pD1nAl7vKkGbQoe/jf7z5sMmTdn2jj529RrhFyoWu+b1uaDVddQvX9sjbxx
            R2XIHE3NbfFX70gvwFk3gEz3kUeo4jPLtDD3wvCJDuLKa4GmqV+Id5u97qc1FLQs
            Lcl7rNNBAb0DannKygeph8J8QsfHFU8aHN6ArHCvziMx/Y4d5VV/e5jBP5ntew2R
            dLceE1rellcaY+deFrGmPjI7C1CZD++ojA5STy7g4jQj0xkDmKN509GTUkI9b2Wy
            6tMylX2BwHSMui+O75JgZuTe1smG0nLTzIDTIaqFMEBb1YcyE9gT4QYiia6hFgxX
            oR6/wWNyPZFcfZUYuP4EgNwkvUE1wP3GEY4D4zVNtcS96WONjiM2ECFvEkXNg6pT
            uDE3KlJRWfsSF1tnJ6pIXvyRkPi9+6w6cBcV+kw+z+W1H4Wm4fwkelEmTAlgpsDw
            pF39te5xkJ8b/YDZvtQmVRCSxSO5orEoDKDYQhC4vhx3zYU0aZxFumK7cE65xOzS
            XgF/R1X2K3mp7WO35hk+69xiDP+3GgBvV/hISlpauhbpZ38OKKl21pHzVhmWclMA
            kFxC7/+11ZRdBxAxBloJx3JDDVsx+yOEhypcASmqKb47U8jOhDbrXJPypJ2bNgk=
            =jnGc
            -----END PGP MESSAGE-----
          fp: CDB1EF76C4F545049CAC882DE4A07D30EC5D6573
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
