# yamllint disable
apiVersion: ENC[AES256_GCM,data:B/0=,iv:5A5F77sHB5C1IV/ZrmeUoLxc+F6SqzFV+gBGFLQbEJE=,tag:mDEIa6I6Fk8FnOelh+k50w==,type:str]
kind: ENC[AES256_GCM,data:O+pOu2RO,iv:Pte1JRxcKCLQMjEYDdQ/edp/elArt//YxX9RUnYmuns=,tag:cF0Gttv4TxSwTsb8iRy+0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0Git79dLOPkyOG4MDWKN,iv:LqAdBhquqVocbWQCRJ3THtJsSPmLxVus9F48r+DywGg=,tag:yJ/QbNjcPTgYQDMtCodzYw==,type:str]
    namespace: ENC[AES256_GCM,data:j43NBDtcSiXfHA==,iv:C4NTTksT+vIuVfNYV5aoPTc50gaZ6QZHs6YQbK8YmZw=,tag:cxz8fdUZzTC5jaXQNp/mkw==,type:str]
stringData:
    objstore.yml: ENC[AES256_GCM,data:H7yqSy82dDDVVljZ1cM4MmHKHm+NXevFV2XW03rXmEUSYmDs3ocvRQ2WJfuRiqJr6UURZpxwvoNgHaZHfvfPGSbaaXuJ2lH/B5RCatllgG5DI3b9idTufXMJJqKQeu6Kn1PxHfXTtAO5aRxRiRBMDzeQUtQ+ScWzRFGTqp21JzvENpEriyWxanv3bIBTsqqf,iv:S0vbZtWtM685TiE8X6/Z0EKOomXS/uh1qm5CX3E2FPU=,tag:MLHGoQ4unNmHjNSuP2Cz3Q==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: D96D04EF03182786C66C1BBC2B6B833C036DBA10
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0DF7VD77L2HARAAtLi5Bnm/FdSqQwc7nDHdPvyWvr+yUQsN5SMJeqniXbOl
            ebhhMC0bz0isSynscy8yvvF7n1WxXsuyhxICmspbBlq6UpwCDUxsmUI36kon/iLe
            T+gm43S/e4NQw5MxBw1ir2Ud866/Nt8x966zVHmLDGmjxcRff2S10vyu8k0026qo
            NHSZdTojwAmevQSLmpLqPRDQpsN/U5F1/hACD8kzoTRIxdvS6u76GZ+Tz0JN5ZJW
            w/HI+XiT8YwOJu7DxiV2Txp3iYQXbPxQL4SvT5WGJqMA106vrWOFHZyt5XjXsinX
            QXJqC7UexKBSLV0FQ4RCT6an2mtVs62n/Q+D7hpQUHofgz9rf6hRlIO1g0fWKfOM
            TNwdnyRA/yPz/dksF6hGzCTZQczlGa1TZ94aAqlQ0CgzpbO2YkV1PUDPxIExq0P+
            rsbrL+PZPlYFwmGdiOrqTHsqjlg7K7A5XnXWPLrlICPpgA0iUuXLyK8KdE1B8Q8T
            pcOFuvkVbm1sKpGBPF8NJWj7Ewy8R9YCcx6d4vc2OxdbhnC7uQ7uPa2s/jmiDolQ
            8mRkiEGpVluE5rrxlvK9QLetku6FFFaFpEGp4UNN1oeHNb1ZJ02lhGNEfGD6snU3
            2JdE1hBKpbuHbE+0NmFkfQZ/yAuSs/vHEouAVsZuPJHBw2Gf8IZvy0N5eCGTf+HS
            XgEsHXjwxdRa47QHJ2F2ernpDz0idocw8L8aLu/zQww87jQy8MQshWoJJKI2DYJG
            WNSW5oWxy8kXo0wMoic2sp2Z1qqC2PgPsYfQP3qoEmJUtRGM/eoVEkeGwArVIYY=
            =H0bV
            -----END PGP MESSAGE-----
        created_at: '2021-10-09T00:53:05Z'
    -   fp: 1AA0AC84A4E1A268F9219DEC3D6F4F5FD1A6E398
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6xGzIm50xo4ARAApFANwdYVTcdr45dGDngDnUhlagAkeNuG0ByRyH2kqEX8
            ZA+IfyiiJD2rs1085PVliAdM7OAgOVvUETLBixkK4eeLbVL1PBD1FC/7j4aXPaxV
            Apl3rz2jXPFhYZuTSfUg4QX7+RAUyTEAFpuGS/Ts4+FxZmZM7xQycP+80+wWmTze
            20roGUpvFWCBFsoUEBswng3CssEOCyvrRZWu54Lee8RLp3ib2qXxqqO42Y+vROb9
            VaJ1ZjFGtqrur9VZAOx1GO0vcF50M5X/K0lGYeMHIADeDO9GfLH+D+37dITp1E+W
            RQHvZllMWdKtwyexAQGJak0ex2fOZPYe7DzwWbqhicqZpsWc1rGXsVxMzwYLOvcg
            quKrW1i9lvoHy7Qrc0AI7cB5I01T67ZYWI1864vikZgZPUWJLKCqoLjw7fHhlvT0
            FPSLMReldq7h4egVqpzYV2ZFblp6ooapyQ+5F3HQxNJ60ohyZcBB+L8xCmQ8SBH3
            xgReSJZmVZo7Lg9Uq+VrvaGVLinVnX43byBz86yDnKXKeyhqR+ujiHcGR9YvpsTD
            hfic0C/ZnovRzOmOuE305m3Iq7puGveAUCPqih4cZjsAu7HlmufeZJQ6aAPgXR7j
            IxyM4Om9x4+q0tQZUZ+8nwwEeuzuSYB2zznrDlr638JyOw9KNz/VTOa6ite0T0fS
            XgFCBsfiNRo9nIrmxQTAObzIRC6syTi+9pl/6Nx/iIFcfXFPMxoBDaibLl1mf3+n
            wPi1zxouHz+5H8MXQ8E7/kCXx0S6FcObSiNyBJLA6zwWR+MwVJUk/0i7PoWn7MY=
            =6tdf
            -----END PGP MESSAGE-----
        created_at: '2021-10-09T00:53:05Z'
    -   fp: CDB1EF76C4F545049CAC882DE4A07D30EC5D6573
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9a6pQFKO0vGAQ/7B3aXex+tOqSPa7eTpV/5Een6oH6cUc2FLC4+bxTRhA0C
            dUWSIt4SKxIvHcMWj0tHfPR/nSVtGN5BeJ2ucZ+MBg8arWqwnSXuX7LzLv7s/VrM
            ouNcvOcDfThjPc8Tc5Voo66onucZdyg7w114ga1tyho5j7iQ6lOr/9bPEGDslc0c
            uDAjlc1uV/bBnCHwo6MeCSLBbGhyMZ341A9rSLAnFY0VIyBGVof0A4XgL36XPyxR
            caEY5VORqCB1hzqZAX1UUXS6V4CTawuRLOGjaC5+pjBp/fcN6KBV9/ums/hitEzI
            kbWZecGDNW5X8X+sFgry2wOO//lrUhWtQ5+EzwkX3Sty4mY6VjvGajEOOJytqP1R
            rYeEiweIDJoA0lOX0In5qpo8JArN+P1RsHy5fVhpHrb13DMvpaeaMY5znrfQMC5L
            Sh3KBxlTwqq+MlinbKUC0FbpUMqIGMxTfwoxQ0uaa8EBFnbH7HocfPiU7k/GkRYA
            kpiTpp5kwZSiwR6S8fRm7egA4FHM2E2yBD8tYoJDuHs2xVxbdogy9isPe/eQRTd7
            I5ew4Xkry6mJ7IRicNRE6AGKM3cUnnlQBLaPqFm46wpdNie4tMJOO2Nxb/yBydY1
            JBB9MPH12ASJySEPhiZhNaXEkYd9iZlH1bQ46tLXZ7ryG/T4mXFXsI5PJnwcrHnS
            XgHFB0M+FB0euYmh20CbtcgHFLu275Cm/Rhto36YISMCcNkYiRuXFsTWkSZSElTZ
            KQZm1GPRfdBzClsVdYNeneBazvwf4b21ralqx7DOBNVcKZmh4IYkHtwQZvH4Vv4=
            =rePx
            -----END PGP MESSAGE-----
        created_at: '2021-10-09T00:53:05Z'
    lastmodified: '2021-10-09T00:53:05Z'
    mac: ENC[AES256_GCM,data:a1Hgm5IkNHJSeFaiFB6bZyXD4eKMIjZcs4m5cEiI2xxdXYviY7vhLTWXJSzXpBYH1Io4dpRCX45j3ew+wIr/wNgD5E4dDFDMkdExnVr0hclDmyzJNvbWTKWIUF81JX48TFODEtf2pYoc2/6G9/ViYYoA5B5Nw802bhGV0+cQN1s=,iv:DjXfW5OPhZhFkOtn9OqYmh5hHCcuncDa9AC4CGcxQkc=,tag:2mgGq+54cLXkq2oz4jsq0Q==,type:str]
