# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: |-
        type: s3
        config:
          bucket: thanos
          endpoint: 10.10.200.240:9000
          access_key: carpenam
          secret_key: Trex4Bob
          insecure: false
          http_config:
            insecure_skip_verify: true
