# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:AF3v9U7+NGNap0BTjwnIHV1PELgbTHLROC7xfthD3ZVxGTs+UWpwqSbZnGgRt0I17A07tzpE3WOvMXknGuUTWILq1tZWzxm60kJugx+cYRnh10ouVge1iedTGiBETnVKxFPJcSqCs/rEyAiA49EE4+K7F2b+SBi5xgV9bMCDeA==,iv:actB+4kwXed/P2a9TgucZmmwl5/WMEs9ne7eRXUtjCo=,tag:C/8VhCw2wf7lPhf9Eo491w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-26T09:03:36Z"
    mac: ENC[AES256_GCM,data:7iOQZaREmO2VKshtA/9WV75TNC3W1MxUn+lGy2zmd54CQgqCrDNNSMOxKuxw7cfF+ba9NE/mQ10FS4CIW1Pa8SbbbNiBuBjPt9E4QVJ+lnLAyYhVCsEabdnRs3nSw0Ja30NOGj2ptSVYE3lyf04oS8ZIIMs+8o3BSX7LFQ4Cjtw=,iv:LmX06H429uJ42vVXDMB8uvGd6ioHs0aDtmpF+4wsPcE=,tag:be/0j76W67xllQaRd1inbA==,type:str]
    pgp:
        - created_at: "2021-09-26T09:03:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0DF7VD77L2HARAAriMXP0BdLkMsLRkWJm6o5JlWbpojumnieMuNXswZHAmV
            t71JjSqd80PfbcBtwKy3w9ZsoVRAq9hLZY6KGNXCwKte/3c9JYGifMoPoNpdBmlm
            r0Ky7zo9H2xWhTQTfOd5xtcwANH8UZCXPsdBf6FuMy+koqDwVEQh24N8/+myjtkO
            leq7CfI7Qijkfb4bHoqYXFLQ8xtwm77C+hKVU+nUSjkr36gthhqMHldqmfI0iYIe
            TGMQcZ2gxv3NEHWCrFrQGbf8LMmOp19eGrDfN30C11jFXaI+oZEiNqQz/HiiMcGi
            MearjNiGmM/LQKCG0HdJzxSoXGE6jq/KQLY9EQo4WDyJ5dj+NJ3IAiE1Ekx4K75S
            U+i+w+AeXU/hSKm96YISYvRQs6O60XQ8qqbe5JKBf6YDUXkJwKp0DsPGfTcT0u6x
            DhmvvBe0g4laYGz5YrpCRYJxRAbVYaZFeY1xN4MzWd7vGZZTwcyqD+VNjhBfT6mE
            E77KKrkMNxrfdex/RjBCEvZRwwoMys/Z8j1wH0v9F+URG0BnbhMQY/Kuda2V/WQP
            DYmgx4qmpsewU1BdB24eGndauX3zxB/eQ+ru0JA8581g8FBW0B50P17QBmePhMFj
            yM6V8aRNnxC4E/lZ9UevQ76QDkf+I5wt2OjnMWdlH0/BDVF6uBe5OB9PDXDBbXHS
            XgF9dxYDwg3Y9WAkXHXDq5ZUznBbWNdmH/H665VwKCO2t6G6KBg4C8fnyHL8f7+0
            M3ER99JYMApUm2Z4gpi1JxyGLzQjfOCjqaScwW6svPKYwzYDgV94NiEmfHpHi08=
            =fDAP
            -----END PGP MESSAGE-----
          fp: D96D04EF03182786C66C1BBC2B6B833C036DBA10
        - created_at: "2021-09-26T09:03:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6xGzIm50xo4ARAAU+K3XYJW9j611CJtabyCvuFlkpfMryHAGeIc+0iwjMUE
            PXA3Eb+7fBBMRSD7WPMj2fhfj74AOS6UQ+TBsPrKqTeZGht/wxMo4bPpQQAIgnqa
            6YH0M84GQSXjFb1EPm4UPfE4sOw1wnVfXf28dxvCcTwFWTWAAKZ8d3BB65Mkz8dw
            +6xvaA8MGJUtTWzGkxNSGqKuQbYKTeF1hyP01FV5MvQvOF+/cER95E3agAPAo43D
            qF0hz+VucyIV+nQR76HiaGNLEtbMqv+07Jmyy0daLt3V3NFXt59HruPPkHs5Yv/8
            lhRk97dMXDovOWUJTx/mcmlNK1FW9kLjCZx79i6iQOPp6WdMSPWtWqB/IRQ46a6g
            dlFk+0cuepsne2kktDnRqzXuMDtd5MI/PhxpQlY2HhwpXFRSJ6gPCg/CMxDr0P/G
            M716PD3SW+HqsHEnKYrnGgLsfjPQWQX3Rl+DEnhvb23mkgwut3uMAl4vclzDrqzZ
            BvHQM3/WGMSHflHyK8wRFiJ6TCBj8nhbDe8TUM5kaxQ1JtlLEXAp43NHEzSko++F
            dGwfbyqXfv4J616ybFXPs75oT37VuNLBWWW4SoyC4c7+WFQrdm/c8r9749sqhAtd
            1foBewjM12XkQK0dt6mfAktcqLjpSAMOe4mhko2SoswxeDJjTiILFGYsImX/LhfS
            5gEcJA4LE/40ZzlpHuKdxmN3DKQRb3vnDOnfa8+D6LNWXDt2vtFTdoAoxtb8PZMm
            HSPt4FSCzHFy7Pr+eyQsUmbk4OpeSGaq5FNHNijv+HijpeJeazyPAA==
            =K4Zl
            -----END PGP MESSAGE-----
          fp: 1AA0AC84A4E1A268F9219DEC3D6F4F5FD1A6E398
        - created_at: "2021-09-26T09:03:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9a6pQFKO0vGARAAi4ytUisZDFfdT8qvw7YxSHIptK8dEOHCSuTDFi4Ky7aY
            iCXNYF4q0KkIrMazQLHos9tQwTK1NbNKlHAW4+f/mTSC2XA5Nd21I4dAlwYVjTer
            C7MUc1IoPa7GbZhAI0VCQuEzBxpY9X5MZnv0XZ3OAdCu6TzJuo+Hpzx+lLkTagYM
            748Sms7pU2GEX71jF5Gi+mkVDuxigfXmOCYI6/Y2KvXFi33suvXjx5IK7E+H5X/L
            rX6nw6yg2aA+6Rna4NQAUoz3H+2bpb9KpyF1rwIeNp7ZIEaRx4yd7oJzZeff3yq9
            vD6d6Dtx2gkcOCEjmMM65UlpqJuMrl7iYbBeeRTFYshivflH3mCfzDjIVaNjNl18
            j+fKZrLV/mEzbrYPPaJauPiGI0DqbthYmn7Oj4EFnuIFD+1zkml4BqwCPIGw6KQT
            louY/ZNnBIzk/P9QD59pfZ2d/YLV4cccQTmxk/Y8vuIsPaJHhpHo8djAbnS5sevm
            T6yjW77jJG3c7nJxYi81xDes7dD0FVDC/jUM7Qo6oKg45YN2SNm3+f/HizvWEQvi
            dmcCeNGwNsMD/ymOCOZu9XWNBGcp1+LGYld+rM6iPWv2+fK2+xdeOO5IXSCayCeR
            O31ylAGIyrazXX5KzpIKB3CDhLkLs1SwisAD2Tj7/XZqnUkNeC/2XfsjYuSZFybS
            XgEopmSLI2kcr+8Oc55hjcglozg5cfjxDB2aXDOvpRNQqFoc3sJjM/YpYlcdMs3l
            WoJpITdfjCxN6D9Aged6F88hBa6ocsAPoCF8+B4hCA8f5fKPQpuVtj4r4TFLdCI=
            =GMPH
            -----END PGP MESSAGE-----
          fp: CDB1EF76C4F545049CAC882DE4A07D30EC5D6573
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
