# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-config
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:22kiNX/UTBK6LDF1cKPgAdmit5TXgtx4MmxYgPXQ3GH68NajYMHZAEnpu9WnoskDiDQXEKzD1g==,iv:jXkCj2hN4yPw4S9MCqQ9Bm2Zbn1PXwHwsWfH0t/qYWU=,tag:XsayyjM1fW+wtpKgaLvV3Q==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:0A0MYLLiXw3daqkSPT7Pp00k46eONDWt3GBTKZctu+UybNE=,iv:/J3ReXFGh4xiKokISMdJBrx/qbsnOeevTVcHOOCGefk=,tag:+oD6VBTpyd9r7BNIpXvlrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-23T03:22:32Z"
    mac: ENC[AES256_GCM,data:DiOBYjJKKd36BjjQ1/P938Tdp21G3UxWDTxKyTJYr+xQ4ZVC/YdklGXAt7H9ah85OtlI5Rp+6QSf/UngPZCs7czqTNlFxgKcOkia0lA+Jr4BKVPx/4t5haBHwpAH44/rpDwtvKQdrHZeMTQnG8amIg0Xt79nrhxcKSH79yszO2g=,iv:NYqRf7XKne0qjhug7B8mYWc4hg68pTgLSlQU51CYjJo=,tag:0o+o/y9WNCQYiT1WN9yS8g==,type:str]
    pgp:
        - created_at: "2021-08-23T03:22:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0DF7VD77L2HAQ//QL2BkAlGXI8e9AuDuuYyCDBkssEnL5ncjPSVsYmn6S12
            Iw6VdemvZkVl5IS6ftOblVocm0Woo5gXX2y1dqYBVu1x6xuNV19Q8Oovgx8V71mz
            9T90KGnsYsidYvcy+SzL7r7nMf9LZ0ark+b0/gys5It1G6JNA12rmacrnFgJB0gw
            lSxcb5T9/u6r4x3UuI76fbaEoKWOxpZP6F1XjE7+9qAx7BmqzfmCOAjB2/HsqsQj
            1Gcel44d2j9t2a3rYIQqDuhLVVyKzuSRkcgY+tRdV7RStNGVI79+0MJYq3jwBv8N
            6RT4iDyMS6WOOiXdUgY6anwj1cWC1Cvbk69wOH5vUQdmU1VG7l6CDFbrTtwnaZyv
            Io426fMSB1YDnszuGH0+TDy9CwenFYQDpILpBjQAVttDosFHZRNhWj1D4k8nZlLF
            i4fEZx9btEMX+AJ6li94cmgS26SIuUCpaVVh0QZ2wHCnS3fP9+nTtrolM3tFWkyA
            PTyG754qCuhLJeWbD/MBuzoMlgoZ+CMhkq3TWVIsJlKzpt3gD6f1QlvvX8HFcRGO
            ujSZ+2a6+7d9hqBUejMOO7drjLl4gMKfGuNq0dPMNoD18nnIpdfugppg4R0Jwr1f
            2aXoESU2BySmA4BBhNqnoRwQ7Jvi0MOGBtWSsivY2HQi0hHt/DkCR27ulQN+MsTS
            XgGvMKaB+YXPz/8iMNKRQYzKRXdB9IvFa/IRzVO8MU9jLUxUR2QvNZrBbv5yK/CI
            B4EyUSUUsRVFAe8aladkLBV0D2iP4M739ipaGtxToYFVGVYDNcmIc6zlt+Vc/iw=
            =NI8b
            -----END PGP MESSAGE-----
          fp: D96D04EF03182786C66C1BBC2B6B833C036DBA10
        - created_at: "2021-08-23T03:22:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6xGzIm50xo4ARAAbdXwCMPp4M2mtqSSKTAqh48aRCU4mMry4T284HQfG8Qc
            ShK7T9wPsVXXW5k4Lb01ccp5gRFdj4KpBWZkLEQk60Ye9JNDYN0XTtUvtv2QUAK4
            0xNwh1fFxGfLwrJb4oVuKQ42r66WR2jhd0otvi9XbUTqSoV6/mHY3vjIUXVaNX8V
            MqfzKfht8s1c5DGg10w7GMW4iYyJHNOYxaGR4wGNJ2jZgX/Jvjk2oNHGxO1Wx9Jb
            iYKR41CK6/JtZDnG+upuYVV7fae5kHOSiyfnSzv+hrb6XamotgrdrWnL9wl8d9YI
            S+3UD7srDILK6lz/3NvJC/exqW6eKLaI0S8OnkQLfjQYxDY9bcT1cT46bjBKE2Rm
            vAv0P3gba7q1Hk8lllgPfJeaghLXztqSIiJJNSeIMozs95IiDymzEl+CksHvwM4F
            D1Gja6CAlkmP0csFzdAoSBU7S0p2svHB71QH/NEjZEDxQZDF+AMT9Raxjdouqk+u
            a50SaG5jMrY5h4fA24nNkuYtXuTUdNLW7C9w2R1XTev2kikDG2wBgySuysta5Zqs
            M3yfWZ82m4n1xNI2ZDB/xRFgBC1iwKwSO3ea1F8S19Yw43xD0YZRdvdiGrfuorzX
            VUHL881Ohg6CBoec3QO/7SV0o5Ip/Z6boRJf8CUwg/KX4evDSrVKKS1/2FvppbXS
            5gE/Vy4kL1UUbQGOotjvFj6LGaGXur440Qm0P/pAHlqO6kV1ugRBr94TgkZlUzC/
            OkvOugcak6PNJ1mTdQkSgLnkl1993I9rYc37ajteuKC6K+JhypDWAA==
            =15wW
            -----END PGP MESSAGE-----
          fp: 1AA0AC84A4E1A268F9219DEC3D6F4F5FD1A6E398
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
