---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-home-assistant-influxdb
  namespace: home
  labels:
    service: home-assistant
    database: influx
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
