---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 11.0.4
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.10.1
      # repository: homeassistant/home-assistant
      # tag: dev
      # pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
      HASS_SECRET_LATITUDE: "${SECRET_HASS_LATITUDE}"
      HASS_SECRET_LONGITUDE: "${SECRET_HASS_LONGITUDE}"
      HASS_SECRET_ELEVATION: "${SECRET_HASS_ELEVATION}"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        # loadBalancerIP: "${LB_HOME_ASSISTANT_IP}"
        externalIPs:
        - "${LB_HOME_ASSISTANT_IP}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          # hajimari.io/url: 
          # hajimari.io/appName: 
          #
          # kubernetes.io/ingress.class: "internal"
        hosts:
        - host: "home.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "home.${SECRET_DOMAIN}"
    monitoring:
      enabled: false
    prometheus:
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: config-home-assistant
    podAnnotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.12.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hosts:
          - host: "vscode.home.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "vscode.home.${SECRET_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /config
    resources:
      requests:
        cpu: 200m
        memory: 1000Mi
      limits:
        memory: 2500Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - plex
            - key: app.kubernetes.io/name
              operator: In
              values:
              - k10
          topologyKey: "kubernetes.io/hostname"
    postgresql:
      enabled: false
      postgresqlDatabase: homeassistant
      postgresqlPassword: "${SECRET_HASS_DB_PASSWORD}"
      postgresqlUsername: "${SECRET_HASS_DB_USERNAME}"
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
    influxdb:
      enabled: false
      architecture: standalone
      database: home_assistant
      authEnabled: false
      updateStrategy: Recreate
      persistence:
        enabled: true
        existingClaim: database-home-assistant-influxdb
