---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-nzbget
  namespace: media
  labels:
    service: nzbget
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
