---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
  labels:
    service: nzbget
spec:
  interval: 6m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/nzbget-testing
      tag: v21.2-r2333
    env:
      TZ: "America/Los_Angeles"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
        - 100
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "download-box"
          # hajimari.io/url:
          # hajimari.io/appName: 
          #
          # nginx.ingress.kubernetes.io/auth-type: basic
          # nginx.ingress.kubernetes.io/auth-secret: media/nginx-basic-auth
          # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/nzbget/organizr-dark.css"></head>';
          #   sub_filter_once on;
        hosts:
        - host: "usenet.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "usenet.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: config-nzbget
      downloads:
        enabled: false
      nas-merged-media:
        enabled: true
        existingClaim: nfs-nas-merged-media-pvc
        mountPath: "/mnt/unionfs"
        # readOnly: true
      nas-downloads:
        enabled: true
        existingClaim: nfs-nas-media-pvc
        mountPath: "/downloads"
        # readOnly: true          
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              # operator: In
              values:
              # - node00
              - node04
    resources:
      requests:
        memory: 260Mi
        cpu: 500m
      limits:
        memory: 7500Mi
