---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-adguard-home
  namespace: network
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
