---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: matrix-helm-values
  namespace: home
spec:
  encryptedData:
    values.yaml: AgCzFRwE+AO7uoibclB11g5o7wCJlq3bfJ3LsaAD3HcP1xM+UzUJrhY7buUsU8/7sZc3vZpXKcgRl0/zlzs8eF9vdHJoyEk9rnWgADmIYiA2/gNN+vYw1KAAhdreWFMCuNGREej35o80pUpeGnfA735jzYf7N7AWm4h2CNgcQLi8U5yNteOMjKcUJPju9kIlWepc7Kpkg6cea9P4osyjPIyjKkf+qQ1ME1zWeANKj4XGs3YbdAScckJyAN+F9qKP59xBu6sUcsbKqyGek+IeU6dtqdYFfgADIv82RSvh2yFolfSmtmWnzEsQNGI2i61PposBPYHUKXq658D1/Y74Vzisq7K7+ZrYbAGktlwSC4iEyeQ85+yW1b0icQYxDMhf3wIpKXJ+4jNghuoqoxXSReSyemCYmmlO7IvskHibfgfbghNZ+obRGqBoU18Jp/7D595q2pDNsZlKcx7n3jyVcIXA7FDphXf5BdegKiuBl9zM5RHp3Dvk6goat7hOydDq7m8SArmK3SgkGFfK0YqE6gRxUXbLrvE9AfuxN1riMVSnuqrB2CfLARdlTZ+AQMVQeCr9vyQkuEcDNAfXzZlfQzqt0uAQTfNrcYwI5KFP8lTMyOuDGOrOPJyDqonIApqNkqie8SWzu7G9w65ZN27w2WHU9kNh8KOFjC9U2CCd4JUMXxFjtM/LDQvkoDv+f3huBKyLLCE+QD6krBo2J3xYjJ6nevC9TlQYcsaKiHA4bthd0aejZmqFIqyExHDBGqAdZbh5EzbaY61Tlcd5UhIDwkG6Og1p9d/o3P26kQ7JJu3NKEGEYiXiPC385k1y0Qc6/ylUuV8PzZaw10nW88biZSMIaJug+dO2f2yCd+hYfuvz87FWzjHY98bKEV9WORo1dqUB4B3UkNHtvI45ag8/310y2iEwWxxPbo8KJ/o0YONkyMIInP229WLwZyWnFB6DXE8uqlGZOakb33KAGQ==
  template:
    metadata:
      creationTimestamp: null
      name: matrix-helm-values
      namespace: home
