---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-sonarr-4k
  namespace: media
  labels:
    service: sonarr-4k
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
