---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr-4k
  namespace: media
  labels:
    service: sonarr-4k
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 6m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.7.1494
      # pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 100
      fsGroup: 568
      supplementalGroups:
        - 100
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          ingress.kubernetes.io/auth-type: "basic"
          ingress.kubernetes.io/auth-secret: "networking/basic-auth"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          # hajimari.io/url:
          # hajimari.io/appName: 
          #
          # nginx.ingress.kubernetes.io/auth-type: basic
          # nginx.ingress.kubernetes.io/auth-secret: media/nginx-basic-auth
          # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          # # nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          # # nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}/oauth2/start"
          # # Custom themes provided by https://github.com/gilbN/theme.park
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter
          #   '</head>'
          #   '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/organizr-dark.css">
          #   <link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/addons/sonarr/sonarr-4k-logo.css">
          #   </head>';
          #   sub_filter_once on;
        hosts:
        - host: "4ktv.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "4ktv.media.${SECRET_DOMAIN}"
      api:
        enabled: true
        primary: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "4ktv.media.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "4ktv.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: config-sonarr-4k
      # nas-merged-media:
      #   enabled: true
      #   existingClaim: nfs-nas-merged-media-pvc
      #   mountPath: "/mnt/unionfs"
      #   # readOnly: true  
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /mnt/NFS/Merged-Media
        mountPath: /mnt/unionfs
        readOnly: false
      remote:
        enabled: true
        type: emptyDir
        mountPath: /data
        # medium: Memory
        # sizeLimit: 1Gi
      rclone:
        enabled: true
        mountPath: "/rclone/rclone.conf"
        subPath: rclone.conf
        type: custom
        volumeSpec:
          secret:
            secretName: rclone-google
    podAnnotations:
      backup.velero.io/backup-volumes: config
    # additionalContainers:
    #   remote:
    #     name: rclone-mount
    #     image: rclone/rclone:1.56
    #     volumeMounts:
    #       - name: remote
    #         mountPath: /data
    #       - name: rclone
    #         mountPath: "/rclone"
    #     env:
    #       - name: config
    #         value: "/rclone/rclone.conf"
    #       - name: remote
    #         value: "google:"
    #       - name: localpath
    #         value: "/data"
    #     command:
    #       - "/bin/sh"
    #       - "-c"
    #       - |
    #         rclone mount \
    #           --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36' \
    #           --config="$config" \
    #           --allow-other \
    #           --gid=100 \
    #           --drive-skip-gdocs \
    #           --vfs-read-chunk-size=64M \
    #           --vfs-read-chunk-size-limit=512M \
    #           --vfs-cache-mode=writes \
    #           --vfs-cache-max-size=5G \
    #           --buffer-size=0M \
    #           --poll-interval=15m \
    #           --dir-cache-time=168h \
    #           --timeout=10m \
    #           --drive-chunk-size=16M \
    #           --umask=002 \
    #           --use-mmap \
    #           -vv \
    #           "$remote" "$localpath"
    #     securityContext:
    #       privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        # cpu: 500m
      limits:
        memory: 1500Mi
