---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: uptimerobot-operator-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://brennerm.github.io/uptimerobot-operator/helm
  timeout: 3m
