apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- descheduler
- home-dns
- intel-gpu-plugin
- kured
# - metrics-server
- node-feature-discovery
- node-problem-detector
- reloader
# - home-dns
