---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-esphome
  namespace: home
  labels:
    service: esphome
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
