---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 128Mi
