---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-node-red
  namespace: home
  labels:
    service: node-red
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
