---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-esphome.yaml
  - config-grocy.yaml
  - config-home-assistant.yaml
  - config-hyperion-ng.yaml
  - config-node-red.yaml
  - config-zigbee2mqtt.yaml
  - data-frigate.yaml
  - database-home-assistant-influxdb.yaml
  - media-frigate.yaml
