---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-frigate
  namespace: home
  labels:
    service: frigate
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
