---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.15
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 3
    env:
      TZ: "America/Los_Angeles"
    service:
      main:
        ports:
          http:
            port: 4000
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${LB_BLOCKY_IP}"
        # externalIPs:
        #   - "${LB_BLOCKY_IP}"
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        externalResolvers:
        - tcp-tls:${SECRET_NEXTDNS_ID}.dns1.nextdns.io:853
        - tcp-tls:${SECRET_NEXTDNS_ID}.dns2.nextdns.io:853
      conditional:
        mapping:
          device.${SECRET_DOMAIN}: udp:1.1.1.1
          vpn.${SECRET_DOMAIN}: udp:1.1.1.1
          cluster.${SECRET_DOMAIN}: udp:10.10.200.1
          iot.${SECRET_DOMAIN}: udp:10.10.100.1
          lan.${SECRET_DOMAIN}: udp:10.10.1.1
          ${SECRET_DOMAIN}: udp:${GATEWAY_IP}
      blocking:
        blackLists:
          ads:
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      clientLookup:
        upstream: udp:${GATEWAY_IP}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    prometheus:
      serviceMonitor:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
