---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-vycontrol
  namespace: networking
  labels:
    service: vycontrol
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
