---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-actions-runner-operator
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://evryfs.github.io/helm-charts/
      chart: github-actions-runner-operator
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: evryfs-oss-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/evryfs/github-actions-runner-operator
      tag: v0.9.2
      # repository: ghcr.io/k8s-at-home/plex
      # tag: v1.22.0.4163-d8c4875dd
      pullPolicy: IfNotPresent
    githubapp:
      enabled: true
      existingSecret: github-runner-app
