---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gaps
  namespace: media
  labels:
    service: gaps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: gaps
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: housewrecker/gaps
      tag: latest
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: true
          # hajimari.io/icon: "mdiTelevisionClassic"
          # hajimari.io/url:
          # hajimari.io/appName: 
        hosts:
        - host: "gaps.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "gaps.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: config-gaps
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
