---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-plex
  namespace: media
  labels:
    service: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
