---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: dev
  namespace: kasten-io
spec:
  locationSpec:
    type: FileStore
    fileStore:
      claimName: nfs-kasten
      path: kasten/dev/k10/migration
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
  type: Location
