---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-radarr
  namespace: media
  labels:
    service: radarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
