---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
  labels:
    service: qbtorrent
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: linuxserver/qbittorrent
      tag: latest
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    service:
      main:
        ports:
          http:
           port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${LB_QBITTORRENT_IP}" 
        # externalIPs:
        # - "${LB_QBITTORRENT_IP}"      
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "qb.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "qb.media.${SECRET_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      nas-merged-media:
        enabled: true
        existingClaim: nfs-nas-merged-media-pvc
        mountPath: "/mnt/unionfs"
        # readOnly: true  
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 200Mi
        # cpu: 500m
      limits:
        memory: 6000Mi
        cpu: 1500m
