---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filestash
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: machines/filestash
      tag: latest@sha256:d0f690b9c610759cc242065a095f8a3baaa91a8ccb2cf018043c71a547680cde
    nameOverride: filestash
    env:
      APPLICATION_URL: "https://filestash.${SECRET_DOMAIN}"
      TZ: "America/Los_Angeles"
    service:
      main:
        ports:
          http:
            port: 8334
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "filestash.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "filestash.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: filestash-config-v1
        mountPath: /app/data/state
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
