---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
  labels:
    service: sonarr
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 15.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 6m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.6.1355
      # pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 100
      fsGroup: 568
      supplementalGroups:
        - 100
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          # hajimari.io/url:
          # hajimari.io/appName: 
          #
          # nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}/oauth2/start"
          # Custom themes provided by https://github.com/gilbN/theme.park
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   proxy_set_header Accept-Encoding "";
          #   sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://gilbn.github.io/theme.park/CSS/themes/sonarr/organizr-dark.css"></head>';
          #   sub_filter_once on;
        hosts:
        - host: "tv.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "tv.media.${SECRET_DOMAIN}"
      api:
        enabled: false
        primary: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "tv.media.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "tv.media.${SECRET_DOMAIN}"
    metrics:
      enabled: false
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v0.6.1
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false
    persistence:
      config:
        enabled: true
        existingClaim: config-sonarr
      # nas-merged-media:
      #   enabled: true
      #   existingClaim: nfs-nas-merged-media-pvc
      #   mountPath: "/mnt/unionfs"
      #   # readOnly: true  
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /mnt/Media/Plex/Merged-Media
        mountPath: /mnt/unionfs
        readOnly: false
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        # cpu: 500m
      limits:
        memory: 3500Mi
