---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-frigate
  namespace: home
  labels:
    service: frigate
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
