---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-overseer
  namespace: media
  labels:
    service: overseer
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
