---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
  labels:
    service: overseer
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: hotio/overseerr
      tag: nightly
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
          # hajimari.io/url:
          # hajimari.io/appName: 
        hosts:
        - host: "requests.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "requests.media.${SECRET_DOMAIN}"
      request:
        enabled: true
        primary: false
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "request.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "request.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: config-overseer
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node00
              - node04
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
