---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
  labels:
    service: overseer
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: hotio/overseerr
      tag: nightly
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      LOG_LEVEL: "info"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      hosts:
      - host: "requests.media.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "requests.media.${SECRET_DOMAIN}"
      additionalIngresses:
      - enabled: true
        nameSuffix: "altname01"
        annotations:
          kubernetes.io/ingress.class: "external"
        hosts:
        - host: "request.media.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "request.media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: config-overseer
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node00
              - node04
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
