---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  removeOSDsIfOutAndSafeToRemove: false
  mon:
    count: 3
    allowMultiplePerNode: false
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  resources:
    mon:
      requests:
        cpu: 35m
        memory: 800Mi
      limits:
        memory: 2048Mi
    osd:
      requests:
        cpu: 35m
        memory: 2048Mi
      limits:
        memory: 6144Mi
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    nodes:
    - name: "nas00"
      devices:
      - name: "nvme0n1p4"
    - name: "node00"
      devices:
      - name: "nvme0n1p1"
    - name: "node01"
      devices:
      - name: "nvme0n1p1"
    - name: "node02"
      devices:
      - name: "nvme0n1p1"
    - name: "node03"
      devices:
      - name: "nvme0n1p4"
    - name: "node04"
      devices:
      - name: "nvme0n1p1"
    - name: "node05"
      devices:
      - name: "nvme0n1p4"