---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-oxidized
  namespace: networking
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
