---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oxidized
  namespace: networking
  labels:
    service: oxidized
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 14.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: oxidized
    controllerType: deployment
    image:
      repository: oxidized/oxidized
      tag: latest
      pullPolicy: Always
    # hostAliases:
    # - ip: ${LB_GITEA_IP}
    #   hostnames:
    #   - "git.dev.${SECRET_DOMAIN}"
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
      CONFIG_RELOAD_INTERVAL: 601
    service:
      main:
        ports:
          http:
           port: 8888
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "router-network"
          # hajimari.io/url:
          # hajimari.io/appName: 
        hosts:
        - host: oxidized.network.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "oxidized.network.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        mountPath: /root/.config/oxidized
        existingClaim: config-oxidized
    podAnnotations:
      backup.velero.io/backup-volumes: config
    probes:
      liveness:
        enabled: false
      startup:
        enabled: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
