---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptimerobot-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://brennerm.github.io/uptimerobot-operator/helm
      chart: uptimerobot-operator
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: uptimerobot-operator-charts
        namespace: flux-system
      interval: 5m
  values:
    uptimeRobotApiKey: "${SECRET_UPTIMEROBOT_API_KEY}"
    disableIngressHandling: true
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 250Mi
