---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dacruz21.github.io/helm-charts
      chart: matrix
      version: 2.7.0
      sourceRef:
        kind: HelmRepository
        name: dacruz21-charts
        namespace: flux-system
      interval: 5m
  suspend: true
  dependsOn:
  - name: sealed-secrets
    namespace: kube-system
  values:
    matrix:
      serverName: elcarpenter.com
      encryptByDefault: all
      adminEmail: "drewmich@elcarenter.com"
      registration:
        enabled: true
    volumes:
      media:
        storageClass: rook-ceph-block
      signingKey:
        storageClass: rook-ceph-block
    postgresql:
      image:
        repository: bitnami/postgresql
        tag: 11.11.0-debian-10-r9
      persistence:
        enabled: true
        storageClass: rook-ceph-block
        size: 8Gi
    ingress:
      enabled: true
      annotations:
        # external-dns.alpha.kubernetes.io/target: 10.20.0.2
        kubernetes.io/ingress.class: "internal"
      hosts:
        synapse: matrix.chat.elcarpenter.com
        riot: element.chat.elcarpenter.com
        federation: elcarpenter.com
      tls:
      - hosts:
        - matrix.chat.elcarpenter.com
        - element.chat.elcarpenter.com
        - elcarpenter.com
        secretName: matrix-cert
    synapse:
      image:
        repository: "matrixdotorg/synapse"
        tag: v1.32.2
    riot:
      image:
        repository: "vectorim/riot-web"
        tag: v1.7.28
    coturn:
      image:
        repository: "instrumentisto/coturn"
        tag: "4.5.1.3"
    mail:
      enabled: true
      from: "matrix@elcarpenter.com"
      relay:
        enabled: true
      # external:
        # host: smtp.holthome.net
        # port: 25
    # bridges:
    #   discord:
    #     enabled: true
    #     image:
    #       repository: halfshot/matrix-appservice-discord
    #       tag: latest
    networkPolicies:
      enabled: false
  valuesFrom:
  - kind: Secret
    name: "matrix-helm-values"
    optional: false
