apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico-system
- default
- kube-system
- home
- flux-system
# - kasten-io
- media
- dev
- monitoring
- networking
- system-upgrade
- tools
# - falco-system
# - gaming
