---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-jackett
  namespace: media
  labels:
    service: jacket
    kasten.io/backup-volume: "enabled"
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
