---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: dev
  namespace: kasten-io
spec:
  frequency: "@daily"
  subFrequency:
    minutes:
    - 0
    hours:
    - 23
    - 11
    weekdays:
    - 0
    days:
    - 1
    months:
    - 1
  retention:
    daily: 7
    weekly: 2
    monthly: 2
    yearly: 0
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - dev
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
        # excludeResources:
        # - name: nfs-media-rocinante-pvc
        #   resource: persistentvolumeclaims
        # - name: nfs-media-serenity-pvc
        #   resource: persistentvolumeclaims
  - action: export
    exportParameters:
      frequency: "@daily"
      profile:
        name: minio
        namespace: kasten-io
      exportData:
        enabled: true
    retention: {}
