# yamllint disable
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-disaster-recovery-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  retention:
    hourly: 4
    daily: 1
    weekly: 1
    monthly: 1
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: kasten-io
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@daily"
        # receiveString: bIzAPpoanmFRkSBfnTozov5CHX4/I3K97xWl3RplcJ0HZcN0vUaaesK0ZtarvPQsf1jKzKuNGU+u7zELhTr93WotnTA5csyiRdO+3fOs7KaOhIIwvWdbHEKI0aD0KaMzbo0Xk0dPwboSlbOQ7NyRmlmFP/yX5np/s2DrMWm3+N6n7NJLGUWrwUC+mUX1KU5K+6FUao21+TVm00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfJa+PK9pzW2/4vBon4DLZ9f/TMqvL3AmLD2A4QDQjGX3OvHcz4H20vpDF9MRkykliNZYKlW8ak4hw2BiXFOV94rtTbl8eptUyjYG6t6j5w0SUxZrUvXR3xQDp2HE3m5iyKZBcw7z3QCFWO3KSTufiHR/tntxmnKAP
        profile:
          name: kasten-io
          namespace: kasten-io
        hooks:
          onSuccess:
            blueprint: kasten-io
            actionName: post-export
        # migrationToken:
        #   name: gaming-migration-token-8kvp9
        #   namespace: kasten-io
        exportData:
          enabled: true
      retention: {}

