---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 6m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    extraEnvVars:
    # - name: slackHookUrl
    #   valueFrom:
    #     secretKeyRef:
    #       name: kured-discord-secret
    #       key: webhook
    configuration:
      startTime: "1:00"
      endTime: "3:00"
      timeZone: "America/Los_Angeles"
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
    metrics:
      create: true
