---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
  - "${SECRET_DOMAIN}"
  - "*.${SECRET_DOMAIN}"
  - "*.media.${SECRET_DOMAIN}"
  - "*.home.${SECRET_DOMAIN}"
  - "*.network.${SECRET_DOMAIN}"
  - "*.admin.${SECRET_DOMAIN}"
  - "*.device.${SECRET_DOMAIN}"
  - "*.backup.${SECRET_DOMAIN}"
  - "*.storage.${SECRET_DOMAIN}"
  - "*.dashboard.${SECRET_DOMAIN}"
  - "*.dashboards.${SECRET_DOMAIN}"
  - "*.monitoring.${SECRET_DOMAIN}"
  - "*.dev.${SECRET_DOMAIN}"
  - "*.chat.${SECRET_DOMAIN}"
  - "*.games.${SECRET_DOMAIN}"
