---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hyperion-ng
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: hyperion-ng
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/hyperhdr
      tag: v17.0.0.0
      # repository: sirfragalot/hyperion.ng
      # tag: 2.0.0-alpha.10-x86_64
      # pullPolicy: Always
    # hostNetwork: true
    env:
      TZ: "America/Los_Angeles"
      PUID: "1000"
      PGID: "100"
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - "${LB_HYPERION_IP}"
        # loadBalancerIP: "${LB_HYPERION_IP}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          # hajimari.io/icon: "mdiTelevisionClassic"
          # hajimari.io/url: 
          # hajimari.io/appName: 
          #
          # kubernetes.io/ingress.class: "internal"
        hosts:
        - host: hyperion.home.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "hyperion.home.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: config-hyperion-ng
    podAnnotations:
      backup.velero.io/backup-volumes: config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
              - node04
              # - k8s-worker-e
    resources:
      requests:
        memory: 250Mi
        # cpu: 500m
      limits:
        memory: 1200Mi
