---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vernemq.github.io/docker-vernemq
      chart: vernemq
      version: 1.6.12
      sourceRef:
        kind: HelmRepository
        name: vernemq-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    serviceMonitor:
      create: true
    service:
      type: LoadBalancer
      loadBalancerIP: "${LB_MQTT_IP}"
      ws:
        enabled: true
      mqtt:
        enabled: true
    additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
    podAntiAffinity: hard
