---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.12
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    eula:
      accept: true
      company: dcplaya
      email: dcplaya@users.noreply.github.com

    global:
      persistence:
        storageClass: ceph-block

    auth:
      k10AdminUsers:
        - ${SECRET_HASS_DB_USERNAME} 
      tokenAuth:
        enabled: false
      basicAuth:
        enabled: true
        htpasswd: ${SECRET_NGINX_BASIC_AUTH}


    clusterName: cluster-1

    ingress:
      create: true
      host: k10.${SECRET_DOMAIN}
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: network-rfc1918-ips@kubernetescrd
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
        external-dns/is-public: "true"
      urlPath: "k10"
      hosts:
        - k10.${SECRET_DOMAIN}
      tls:
        enabled: true
        secretName: k10-tls

    grafana:
      enabled: false
