apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
- prometheus-rule.yaml
- service-monitor.yaml
# - policies
# # TODO Enable on cluster re-install
# - profiles
